name: Deploy

on:
  release:
    types: [published]

jobs:
  make:
    name: Make
    runs-on: windows-latest
    environment: Compile
    steps:
      - name: ðŸ“¦ Prepate Git Repo
        uses: actions/checkout@v2.3.4

      - name: ðŸ“¦ Install npm
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          architecture: x64

      - name: ðŸ“¦ Package Executable
        run: |
          npm i
          npm run prepare
          npm run make

      - name: ðŸš€ Deploy Installer to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'out/make/**/*.exe;out/make/**/*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
