name: Deploy

on:
  release:
    types: [published]

jobs:
  make:
    name: Make
    runs-on: windows-latest
    environment: Electron Make
    steps:
      - name: ðŸ“¤ Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: ðŸ“š Install npm
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 14
          architecture: x64

      - name: âœ” Compile with npm
        run: |
          npm ci

      - name: ðŸ”„ Rebuild with Electron
        run: |
          npm run rebuild

      - name: ðŸ“¦ Package Executable
        run: |
          npm run make

      - name: ðŸš€ Deploy to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'out/make/**/*.exe;out/make/**/*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
